<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Alain Silvestre" />

<meta name="date" content="2016-04-14" />

<title>PA1_template</title>

<script src="PA1_template_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="PA1_template_files/highlight/default.css"
      type="text/css" />
<script src="PA1_template_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>




</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="PA1_template_files/navigation-1.0/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">


<h1 class="title">PA1_template</h1>
<h4 class="author"><em>Alain Silvestre</em></h4>
<h4 class="date"><em>14 April 2016</em></h4>

</div>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>It is now possible to collect a large amount of data about personal movement using activity monitoring devices such as a Fitbit, Nike Fuelband, or Jawbone Up. These type of devices are part of the ???quantified self??? movement ??? a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. But these data remain under-utilized both because the raw data are hard to obtain and there is a lack of statistical methods and software for processing and interpreting the data.</p>
<p>The data used for the below analysis are colected from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.</p>
<p>The data set can be downloaded as a zip file (activity.zip) from the following github link: <a href="https://github.com/rdpeng/RepData_PeerAssessment1" class="uri">https://github.com/rdpeng/RepData_PeerAssessment1</a></p>
<p>The variables included in the dataset are:</p>
<pre><code>steps:    Number of steps taking in a 5-minute interval (missing values are coded as NA)
date:     The date on which the measurement was taken in YYYY-MM-DD format
interval: Identifier for the 5-minute interval in which measurement was taken</code></pre>
<p>The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this dataset. This covers observations for 61 days, 12 observations per hours for 24 hours.</p>
<p>Make sure the data set is made available in your R working directory</p>
</div>
<div id="step-1---load-and-pre-processing-of-data" class="section level2">
<h2>Step 1 - Load and pre-processing of data</h2>
<p>Read and load the dataset into your R environment Some pre-processing is required to transform date and time Note: make use of UTC time zone in all computation to avoid daytime saving differences (time change occurs end October)</p>
<pre class="r"><code># Read Data
data1 &lt;- read.csv(&quot;./activity.csv&quot;, header=TRUE)
# format date
data1$date &lt;- as.Date(data1$date)
#create a vector with time value corresponding to interval and append it as a new column
DateTime &lt;- seq( ISOdatetime(2012,10,1,0,0,0, tz=&quot;UTC&quot;), ISOdatetime(2012,11,30,23,55,0,tz=&quot;UTC&quot;), by=(60*5))
Time &lt;- strftime(DateTime, format = &quot;%H:%M:%S&quot;, tz=&quot;UCT&quot;)
data1 &lt;- cbind(data1, Time)</code></pre>
</div>
<div id="step-2---total-number-of-steps-per-day" class="section level2">
<h2>Step 2 - Total number of steps per day</h2>
<p>Investigate the total number of steps per day by computing the sum of steps for each day between Oct 1st and Nov 30th, 2012</p>
<pre class="r"><code>data2 &lt;- with(data1, tapply(steps, date, sum, na.rm=TRUE))
summary(data2)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0    6778   10400    9354   12810   21190</code></pre>
<p>The total number of steps per day is most frequently in the range [9000 - 15.000] with an average of 9354 steps per day and the median at 10400 steps per day</p>
<pre class="r"><code>hist(data2, breaks=10, xlab=&quot;Total number of steps per day&quot;, col=&quot;green&quot;, main=&quot;Histogram of daily total number of steps, Oct-Nov 2012&quot;)
abline(v=median(data2), col=&quot;blue&quot;, lwd=4)
legend(&quot;topright&quot;, lty=1, col=&quot;blue&quot;, legend=&quot;median&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-3-1.png" /><!-- --></p>
</div>
<div id="steps-3---average-daily-activity-pattern" class="section level2">
<h2>Steps 3 - average daily activity pattern</h2>
<p>First compute the average number of steps per time interval (average is taken between all 61 days of the sample) Convert the result into a dataframe with a time column to allow for graphic plotting</p>
<pre class="r"><code>data3 &lt;- with(data1, tapply(steps, interval, mean, na.rm=TRUE))
df3 &lt;- data.frame(time=names(data3), mean=data3)
df3$time &lt;- as.POSIXct(df3$time, tz=&quot;UTC&quot;, format=&quot;%H:%M:%S&quot;)

# display max value
df3[df3$mean == max(df3$mean), 2]</code></pre>
<pre><code>##      835 
## 206.1698</code></pre>
<p>The average daily activity pattern shows a maximum number of steps around 8:35 in the morning (with a peak at 206 steps) This peak in daily activity correspond to interval number 104</p>
<pre class="r"><code>plot(data3, type=&quot;l&quot;, col=&quot;red&quot;, main=&quot;Average number of steps per 5-minutes interval, averaged across all days&quot;, xlab=&quot;Time interval index&quot;, ylab=&quot;Average number of steps&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-5-1.png" /><!-- --></p>
</div>
<div id="steps-4---missing-values" class="section level2">
<h2>Steps 4 - missing values</h2>
<p>There are 2304 records with missing steps values</p>
<pre class="r"><code>MissingData &lt;- data1[is.na(data1$steps), ]
nrow(MissingData)</code></pre>
<pre><code>## [1] 2304</code></pre>
<pre class="r"><code>#replace missing steps values by the mean value or corresponding interval

data4 &lt;- data1
for ( i in 1:nrow(data4)) {
  if ( is.na(data4$steps[i])) {
  data4$steps[i] &lt;- df3$mean[data4$Time[i]]  
  }
}

# compure new average daily activity
data4b &lt;- with(data4, tapply(steps, date, sum, na.rm=TRUE))
summary(data4b)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      41    9819   10770   10770   12810   21190</code></pre>
<p>Replacing the missing values by the average number of steps for the given interval has limited effect on the total number of steps taken per day, pushing the mean and median to 10770 steps (average number of steps increase by ~15% from 9354 to 10770)</p>
<pre class="r"><code>hist(data4b, breaks=10, xlab=&quot;Total number of steps per day&quot;, col=&quot;green&quot;, main=&quot;Histogram of daily total number of steps, Oct-Nov 2012&quot;)
abline(v=median(data4b), col=&quot;blue&quot;, lwd=4)
legend(&quot;topright&quot;, lty=1, col=&quot;blue&quot;, legend=&quot;median&quot;)
mtext(text=&quot;Missing values replaced by average  for the given interval&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-7-1.png" /><!-- --></p>
</div>
<div id="steps-5---differences-between-weekdays-and-weekends-activity-paterns" class="section level2">
<h2>Steps 5 - differences between weekdays and weekends activity paterns</h2>
<p>Add a column indicating the day of the week to data file (starting from file with missing values replaced)</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>wd &lt;- weekdays(data4$date)
data5 &lt;- cbind(data4, wd)

# replace day of the week by factor
data5$wd &lt;- ifelse(data5$wd %in% c(&quot;Saturday&quot;,&quot;Sunday&quot;), &quot;Weekend&quot;,&quot;Weekday&quot;)
data5$wd &lt;- factor(data5$wd, levels = c(&quot;Weekday&quot;,&quot;Weekend&quot;))

# split in two dataset and compute average values
data5a &lt;- filter(data5, wd == &quot;Weekend&quot;)
df5a &lt;- with(data5a, tapply(steps, interval, mean, na.rm=TRUE))

data5b &lt;- filter(data5, wd == &quot;Weekday&quot;)
df5b &lt;- with(data5b, tapply(steps, interval, mean, na.rm=TRUE))</code></pre>
<p>A split of activity between weekdays and weekends shows more “active” intervals during the weekends. The absolute maximum number of steps still occurs during weekdays in the morning.</p>
<pre class="r"><code>par(mfcol=c(2,1))

plot(df5a, type=&quot;l&quot;, col=&quot;red&quot;, main=&quot;Weekend&quot;, xlab=&quot;Time interval index&quot;, ylab=&quot;Average number of steps&quot;)

plot(df5b, type=&quot;l&quot;, col=&quot;red&quot;, main=&quot;Weekdays&quot;, xlab=&quot;Time interval index&quot;, ylab=&quot;Average number of steps&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-9-1.png" /><!-- --></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
